# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Denforcer.fail=false --file pom.xml
    - name: Build & Publish Image
      run: echo Build Image   

  deploydev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Development
        run: echo app deployed en dev

  testdev:
    needs: deploydev
    runs-on: ubuntu-latest
    steps:
      - name: functional test on jenkins
        uses: juananmora/triggerjenkinsjob@v1
        with:
          urljenkins: 'http://mat.qualitat.solucions.gencat.cat/jenkins'
          user: 'devsecops'
          password: ${{ secrets.JENKINS_TOKEN }}
          job: 'functional-test-selenium-jenkinsfile'
          params: '{"urlrepo":"http://gitea.gitea/devsecops/functional-test.git", "entorno":"desarrollo", "urlapp":"http://petclinic-frontend-angular.petclinic/","rama":"main", "umbral":"60"}'

  deploypre:
    needs: testdev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PRE
        run: echo app deployed en PRE
  testpre:
    needs: deploypre
    runs-on: ubuntu-latest
    steps:
      - name: functional test on jenkins
        uses: juananmora/triggerjenkinsjob@v1
        with:
          urljenkins: 'http://mat.qualitat.solucions.gencat.cat/jenkins'
          user: 'devsecops'
          password: ${{ secrets.JENKINS_TOKEN }}
          job: 'functional-test-selenium-jenkinsfile'
          params: '{"urlrepo":"http://gitea.gitea/devsecops/functional-test.git", "entorno":"preproduccion", "urlapp":"http://petclinic-frontend-angular.petclinic/","rama":"main", "umbral":"50"}'


  deploypro:
    needs: testpre
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PRO
        run: echo app deployed en PRO

  testpro:
    needs: deploypro
    runs-on: ubuntu-latest
    steps:
      - name: functional test on jenkins
        uses: juananmora/triggerjenkinsjob@v1
        with:
          urljenkins: 'http://mat.qualitat.solucions.gencat.cat/jenkins'
          user: 'devsecops'
          password: ${{ secrets.JENKINS_TOKEN }}
          job: 'functional-test-selenium-jenkinsfile'
          params: '{"urlrepo":"http://gitea.gitea/devsecops/functional-test.git", "entorno":"produccion", "urlapp":"http://petclinic-frontend-angular.petclinic/","rama":"main", "umbral":"20"}'


