# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Pipeline MAT

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: echo Maven
    - name: Build & Publish Image
      run: echo Build Image   

  scansonar:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: functional test on jenkins
        uses: juananmora/triggerjenkinsjob@main
        with:
          urljenkins: 'http://mat.qualitat.solucions.gencat.cat/jenkins'
          user: 'devsecops'
          password: ${{ secrets.JENKINS_TOKEN }}
          job: 'multibranch-sonar/springboot'
          params: '{"REPO_URL":"http://gitea.gitea/petclinic/petclinic-backend-springboot.git", "projectkey":"petclinic-backend-springboot", "rama":"master"}'  
  deploydev:
    needs: scansonar
    runs-on: ubuntu-latest
    environment: desarrollo
    steps:
      - name: Deploy Development
        run: echo app deployed en dev

  testdev:
    needs: deploydev
    runs-on: ubuntu-latest
    steps:
      - name: functional test on jenkins
        uses: juananmora/triggerjenkinsjob@main
        with:
          urljenkins: 'http://mat.qualitat.solucions.gencat.cat/jenkins'
          user: 'devsecops'
          password: ${{ secrets.JENKINS_TOKEN }}
          job: 'functional-test-selenium-jenkinsfile'
          params: '{"repositorio":"http://gitea.gitea/devsecops/functional-test.git", "entorno":"desarrollo", "urlapp":"http://petclinic-frontend-angular.petclinic/","rama":"main", "umbral":"60"}'
  apitest:
    needs: deploydev
    runs-on: ubuntu-latest
    steps:
      - name: functional test on jenkins
        uses: juananmora/triggerjenkinsjob@main
        with:
          urljenkins: 'http://mat.qualitat.solucions.gencat.cat/jenkins'
          user: 'devsecops'
          password: ${{ secrets.JENKINS_TOKEN }}
          job: 'backend-test-postman-jenkinsfile'
          params: '{"REPO_URL":"http://gitea.gitea/devsecops/backend-test-java.git", "APP_NAME":"template"}'

 
  deploypre:
    needs: [testdev,apitest]
    runs-on: ubuntu-latest
    environment: preproduccion
    steps:
      - name: Deploy PRE
        run: echo app deployed en PRE
  testpre:
    needs: deploypre
    runs-on: ubuntu-latest
    steps:
      - name: functional test on jenkins
        uses: juananmora/triggerjenkinsjob@main
        with:
          urljenkins: 'http://mat.qualitat.solucions.gencat.cat/jenkins'
          user: 'devsecops'
          password: ${{ secrets.JENKINS_TOKEN }}
          job: 'functional-test-selenium-jenkinsfile'
          params: '{"repositorio":"http://gitea.gitea/devsecops/functional-test.git", "entorno":"preproduccion", "urlapp":"http://petclinic-frontend-angular.petclinic/","rama":"main", "umbral":"50"}'

  performance:
    needs: deploypre
    runs-on: ubuntu-latest
    steps:
      - name: functional test on jenkins
        uses: juananmora/triggerjenkinsjob@main
        with:
          urljenkins: 'http://mat.qualitat.solucions.gencat.cat/jenkins'
          user: 'devsecops'
          password: ${{ secrets.JENKINS_TOKEN }}
          job: 'performance-test-jmeter-pipeline'
          params: '{"repositorio":"http://gitea.gitea/devsecops/functional-test.git"}'

  deploypro:
    needs: [testpre,performance]
    runs-on: ubuntu-latest
    environment: produccion
    steps:
      - name: Deploy PRO
        run: echo app deployed en PRO

  testregresion:
    needs: deploypro
    runs-on: ubuntu-latest
    steps:
      - name: functional test on jenkins
        uses: juananmora/triggerjenkinsjob@main
        with:
          urljenkins: 'http://mat.qualitat.solucions.gencat.cat/jenkins'
          user: 'devsecops'
          password: ${{ secrets.JENKINS_TOKEN }}
          job: 'functional-test-selenium-jenkinsfile'
          params: '{"repositorio":"http://gitea.gitea/devsecops/functional-test.git", "entorno":"produccion", "urlapp":"http://petclinic-frontend-angular.petclinic/","rama":"regresion", "umbral":"20"}'

